#!/usr/bin/env python3
"""
Write the current process environment to a .env file.

By default only includes variables used by this project:
  - every name starting with PRONUNCIATION_
  - HF_HOME (if set)

Usage (from repo root, after exporting vars in your shell):

  uv run python scripts/capture_env_to_dotenv.py
  uv run python scripts/capture_env_to_dotenv.py --output .env.local
  uv run python scripts/capture_env_to_dotenv.py --full   # entire os.environ (large)

PowerShell: run the same command in the same session where you set $env:... variables.
Bash: run after `source scripts/bake-env.sh` or `export ...`.
"""

from __future__ import annotations

import argparse
import os
from datetime import datetime, timezone
from pathlib import Path


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _format_value(value: str) -> str:
    if value == "":
        return ""
    if "\n" in value or "\r" in value:
        escaped = (
            value.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\r", "\\r")
        )
        return f'"{escaped}"'
    unsafe = set(' \t#"\'')
    if any(c in value for c in unsafe) or value.startswith("$"):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


def _collect_project_keys(environ: dict[str, str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for key, value in environ.items():
        if key.startswith("PRONUNCIATION_"):
            out[key] = value
    if "HF_HOME" in environ:
        out["HF_HOME"] = environ["HF_HOME"]
    return out


def _collect_full(environ: dict[str, str]) -> dict[str, str]:
    return dict(environ)


def main() -> None:
    parser = argparse.ArgumentParser(description="Snapshot environment variables into a .env file.")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=_repo_root() / ".env",
        help="Destination file (default: <repo>/.env)",
    )
    parser.add_argument(
        "--full",
        action="store_true",
        help="Include every variable in os.environ (can be large; may contain secrets).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print to stdout instead of writing a file.",
    )
    args = parser.parse_args()

    environ = {k: v for k, v in os.environ.items() if isinstance(v, str)}
    if args.full:
        data = _collect_full(environ)
    else:
        data = _collect_project_keys(environ)

    lines: list[str] = [
        "# Generated by scripts/capture_env_to_dotenv.py",
        f"# UTC: {datetime.now(timezone.utc).isoformat()}",
        "#",
    ]
    if args.full:
        lines.append("# Mode: --full (all variables from the capturing process)")
    else:
        lines.append("# Mode: project (PRONUNCIATION_* and HF_HOME if set)")
    lines.append("")

    for key in sorted(data.keys()):
        val = data[key]
        lines.append(f"{key}={_format_value(val)}")

    text = "\n".join(lines) + "\n"

    if args.dry_run:
        print(text, end="")
        return

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    print(f"Wrote {len(data)} variables to {args.output.resolve()}")


if __name__ == "__main__":
    main()
